### ISSUE TITLE
Where do I put my own Djot plugin?

### ISSUE THREAD

**Issue by iacore** [lumeland/experimental-plugins#38]
I have [modified](https://github.com/iacore/djot.js) djot.js to work better than the original one that is included in [my last PR](#35).

You can now write something like this:

```
:::: details
::: summary
you can have real elements!
:::
much better
::::
```

I find this very very useful, and want to share this. However, this is not part of the official Djot spec yet (still debated on their /issues/).

Where do I put this?

***

The usage is like this:

```ts
import djot from "https://raw.githubusercontent.com/iacore/djot.js/e90edeb/lume-djot-plugin.ts";
const site = lume();
site.use(djot());
```

**Comment by oscarotero** [comment]
Hi.
An option is to publish your fork in deno.land/x, for example. Then, the Lume plugin can use the Deno version instead of NPM version.

**Comment by oscarotero** [comment]
@iacore Ok, I thought you were referring only to the djot.js dependency, not the Lume plugin that use it.

This *experimental-plugins* repository is for plugins that may be included at some point to the Lume repository and become "official". But there are other plugins made by the community that are published in different repositories. In the [Plugins page of lume.land](https://lume.land/plugins/?status=all), you can see below other 3rd party plugins. So yes, a Djot plugin could be a 3rd party plugin included in this page.

Also, an `awesome-lume-plugins` page is a great idea, I'll work on that.

Regarding to publish method, https://raw.githubusercontent.com/ is perfectly valid, but maybe some people are hesitant to use it, because the repository can be moved or removed at some point and the import would stop working. land/x ensure inmutability and the code will be available always, even if you decide to remove the repository. Another option is jsdelivr, that I use for LumeCMS and it works with tags of GitHub repositories. For example, https://cdn.jsdelivr.net/gh/lumeland/cms@0.5.0/ serves the content [of the tag v0.5.0](https://github.com/lumeland/cms/releases/tag/v0.5.0)

**Comment by iacore** [comment]
> Another option is jsdelivr, that I use for LumeCMS and it works with tags of GitHub repositories. For example, https://cdn.jsdelivr.net/gh/lumeland/cms@0.5.0/ serves the content [of the tag v0.5.0](https://github.com/lumeland/cms/releases/tag/v0.5.0)

Does JSDelivr go away when the repository is moved or removed?

**Comment by oscarotero** [comment]
Yes, [according to this](https://www.jsdelivr.com/github)

> By using jsDelivr CDN URLs you get better performance globally thanks to our multi-CDN infrastructure. We also permanently cache all files to ensure reliability, even if your files get deleted from Github they will continue to work on jsDelivr without breaking any sites using them.

**Comment by iacore** [comment]
Understood. You can close this issue now or when `awesome-lume-plugins` is done.

**Comment by oscarotero** [comment]
I've created this https://github.com/lumeland/awesome-lume
Feel free to PR your plugins there!
